# Generated by Django 3.0.8 on 2020-08-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raincheck', '0002_auto_20200809_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='region',
        ),
    ]
