# Generated by Django 3.0.8 on 2020-11-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincheck', '0005_auto_20200924_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
