# Generated by Django 3.0.8 on 2020-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincheck', '0006_auto_20201120_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants'),
        ),
    ]
