# Generated by Django 3.0.8 on 2020-12-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincheck', '0008_add_longitude_and_latitude_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='latin_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
